
import Phase1.Post;
import Phase1.User;
import java.awt.Color;
import java.util.ArrayList;
import phase2.NetworkAnalysis;
import phase2.PostSearch;
import phase2.Vizualizer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author SHEREF ZEDAN
 */
public class part2 extends javax.swing.JFrame {

    private User[] user1;

    /**
     * Creates new form part2
     */
    public part2(User[] user) {
        initComponents();
        user1 = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        Vizualizer = new javax.swing.JButton();
        GetMutul = new javax.swing.JButton();
        Analysis = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        mutual2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        mutul1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        AnalysisText = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Search.setForeground(new java.awt.Color(51, 51, 255));
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        searchText.setColumns(20);
        searchText.setRows(5);
        jScrollPane1.setViewportView(searchText);

        output.setColumns(20);
        output.setRows(5);
        jScrollPane2.setViewportView(output);

        Vizualizer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Vizualizer.setForeground(new java.awt.Color(51, 51, 255));
        Vizualizer.setText("Vizualizer");
        Vizualizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VizualizerActionPerformed(evt);
            }
        });

        GetMutul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GetMutul.setForeground(new java.awt.Color(51, 51, 255));
        GetMutul.setText("GetMutul");
        GetMutul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetMutulActionPerformed(evt);
            }
        });

        Analysis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Analysis.setForeground(new java.awt.Color(51, 51, 255));
        Analysis.setText("Analysis");
        Analysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalysisActionPerformed(evt);
            }
        });

        mutual2.setColumns(20);
        mutual2.setRows(5);
        jScrollPane3.setViewportView(mutual2);

        mutul1.setColumns(20);
        mutul1.setRows(5);
        jScrollPane4.setViewportView(mutul1);

        AnalysisText.setColumns(20);
        AnalysisText.setRows(5);
        jScrollPane5.setViewportView(AnalysisText);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("getSuggerstions");
        jButton1.setSelected(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GetMutul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Vizualizer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Analysis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Vizualizer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GetMutul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Analysis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        try {
            output.setText(null);
            String f = searchText.getText();
            if (f == null || f.isBlank()) {
                output.append("please insert text to search\n");
                output.setForeground(Color.red);
                return;
            }
            PostSearch x = new PostSearch();
            x.searchForPost(user1, f);
            ArrayList<Post> p = x.getPosts();
            for (int i = 0; i < p.size(); i++) {
                output.append(p.get(i).toString() + "\n");
                output.setForeground(Color.green);
            }
        } catch (Exception e) {
            output.append(e.toString());
            output.setForeground(Color.red);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void VizualizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VizualizerActionPerformed
        try {
            Vizualizer v = new Vizualizer(user1);
            v.show();

            output.setForeground(Color.green);
        } catch (Exception e) {
            output.append(e.toString());
            output.setForeground(Color.red);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_VizualizerActionPerformed

    private void GetMutulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetMutulActionPerformed
        try {
            output.setText(null);
            String r = mutul1.getText();
            String s = mutual2.getText();
            if ((r == null || r.isBlank()) && (s == null || s.isBlank())) {
                output.append("please insert text to mutul\n");
                output.setForeground(Color.red);
                return;
            }

            User user2 = new User(1, r);
            User user3 = new User(2, s);
            NetworkAnalysis ne = new NetworkAnalysis();
            output.append(ne.getMutul(user2, user3).toString());
            output.setForeground(Color.green);
        } catch (Exception e) {
            output.append(e.toString());
            output.setForeground(Color.red);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_GetMutulActionPerformed

    private void AnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalysisActionPerformed
        try {
            output.setText(null);
            NetworkAnalysis ne = new NetworkAnalysis();

            AnalysisText.append("topActive\n" + ne.getTopActive(user1).toString() + "\n");
            AnalysisText.append("topInfluencer\n" + ne.getTopInfluencer(user1).toString() + "\n");
            AnalysisText.setForeground(Color.green);
        } catch (Exception e) {
            output.append(e.toString());
            output.setForeground(Color.red);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_AnalysisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            output.setText(null);
            String r = mutul1.getText();
            if (r == null || r.isBlank()) {
                output.append("please insert text to search\n");
                output.setForeground(Color.red);
                return;
            }
            User user2 = new User(1, r);
            NetworkAnalysis ne = new NetworkAnalysis();
            output.append(ne.getSuggerstions(user2).toString() + "\n");
            output.setForeground(Color.green);
        } catch (Exception e) {
            output.append(e.toString());
            output.setForeground(Color.red);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Analysis;
    private javax.swing.JTextArea AnalysisText;
    private javax.swing.JButton GetMutul;
    private javax.swing.JButton Search;
    private javax.swing.JButton Vizualizer;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea mutual2;
    private javax.swing.JTextArea mutul1;
    private javax.swing.JTextArea output;
    private javax.swing.JTextArea searchText;
    // End of variables declaration//GEN-END:variables
}
